# Generated by Django 5.1.1 on 2024-10-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_alter_date_date_alter_date_location_alter_date_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DateTable',
        ),
    ]
